### ISSUE TITLE
Jest 27 error: The "data" argument must be of type string

### ISSUE THREAD

**Issue by fregante** [danwang/yaml-jest#5]
I think this change is affecting `yaml-jest`: https://github.com/facebook/jest/pull/10926

```
  ● Test suite failed to run

    TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object

      at Object.getCacheKey (node_modules/yaml-jest/index.js:15:62)
      at ScriptTransformer._getCacheKey (node_modules/@jest/transform/build/ScriptTransformer.js:280:41)
      at ScriptTransformer._getFileCachePath (node_modules/@jest/transform/build/ScriptTransformer.js:351:27)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:588:32)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:758:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:815:19)
```

it points to 

```js
var getCacheKey = function getCacheKey(fileData, filePath, configString, options) {
  return _crypto2.default.createHash('md5').update(fileData).update(configString).digest('hex');
};
```

`configString` is a string in Jest v26 but an object in Jest v27. Should this be changed to

```diff
var getCacheKey = function getCacheKey(fileData, filePath, configString, options) {
-  return _crypto2.default.createHash('md5').update(fileData).update(configString).digest('hex');
+  return _crypto2.default.createHash('md5').update(fileData).update(JSON.stringify(configString)).digest('hex');
};
```

**Comment by elijahmanor** [comment]
I upgraded to Jest 27 and am getting the same error as well. Thanks for submitting the issue.

**Comment by sumwatshade** [comment]
@fregante @elijahmanor I threw [jest-transform-yaml](https://github.com/sumwatshade/jest-transform-yaml) together to solve for the same issue. I plan to maintain this one with future Jest updates where possible!

**Comment by peterboyer** [comment]
@sumwatshade Just a warning to you and other developers stumbling onto this problem also: Installing your package `jest-transform-yaml` introduced the now deprecated `crypto` package to my `node_modules` which then caused a really hard to diagnose error being thrown when attempting run a project with `vite`.

**Comment by sumwatshade** [comment]
@ptboyer I assume you are seeing this only in Node 17, where Crypto is deprecated? Using Node 16 should be fine, but let me run against Node current as well in my CICD

**Comment by sumwatshade** [comment]
@ptboyer apologies for that issue leading you down a rabbit hole, I have patched the above and took this opportunity to release  [v1.0.0](https://github.com/sumwatshade/jest-transform-yaml/releases/tag/v1.0.0) so that I can better manage Node versions within the project.

Do you have a minimal example of this? I would like to include some integration tests in my module to prevent issues like that in the future 😄

**Comment by peterboyer** [comment]
@sumwatshade Was just as simple as having a basic `vite` project (in my case was with react, as pre following the vite: getting started docs) and then installing `jest-transform-yaml` and attemtping to run `yarn dev` which would start `vite` as a development environment. :slightly_smiling_face:
